### ISSUE TITLE
[suggestion] add more JVM language wrappers

### ISSUE THREAD

**Issue by enderger** [QuiltMC/quilt-kotlin-libraries#15]
While Kotlin is certainly the most prevalent alternative language on the JVM, it certainly isn’t the only one. It might be wise to add supports for some of these, likely using other repos.

Currently, we think these targets have merit:
- Scala : an “industrial” language taking more functional influence, has official bindings in Fabric (though they have gone unmaintained).
- Clojure : a dynamic Lisp dialect, influenced many other languages and woefully underrepresented in Minecraft modding. A mod called ClojureWrapper provides some support for the language, but unfortunately lack of visibility makes language bindings like it harder to trust to stay afloat.
- Groovy : kind of in the same boat as Scala, but an active fork of the support library exists.

We apologise if this is the wrong repo to discuss this in, but it seems to make the most sense for the suggestion.

**Comment by SilverAndro** [comment]
There was discussion of this previously while drafting the original kotlin RFC, if I remember correctly it was decided against due to lack of knowledge or demand in the modding space for those languages

**Comment by Oliver-makes-code** [comment]
Other languages require people that know them and are willing to contribute, which is a slim amount of people, and it's unreasonable to have stuff that will be used by few people
