### ISSUE TITLE
Math Ops

### ISSUE THREAD

**Issue by SilverAndro** [QuiltMC/quilt-kotlin-libraries#2]
## Intro:

Minecraft has several custom math types, such as `Vec3d`, `Vec3i`, `Vec2i`, Matrix types, ect. These types often have operations that can be applied on them, such as `Vec3d.add(Vec3d)`. These can be improved in Kotlin through the use of [operator overloading](https://kotlinlang.org/docs/operator-overloading.html) so that operations such as `Vec3d + Ved3d` may be preformed instead.

## Existing work:
- At this time I am unable to locate existing work on such an API

**Comment by leocth** [comment]
I'd written some extensions before - it had some basic stuff like destructuring, math operations and so on

[example 1](https://github.com/leocth/gravity-guns/blob/1.17/src/main/kotlin/com/leocth/gravityguns/util/ext/VectorExtensions.kt)

[example 2](https://github.com/ReMod-Studios/remod-core/blob/cf066c5d9652f56dad1bd024ad5767899f8cd1af/common/src/main/kotlin/io/github/remodstudios/remodcore/Extensions.kt#L43-L48)
