### ISSUE TITLE
Type alias/receiver remapping does not work

### ISSUE THREAD

**Issue by SilverAndro** [QuiltMC/quilt-kotlin-libraries#27]
(Should have opened this sooner, whoops!)

Right now the QSL wrappers are broken due to them not being included as `modApi` in loom. Sadly due to terrible loom decisions, its not possible to directly add them as such, resulting in errors at configuration time.

Two solutions to this problem are possible:

- Rewrite the buildscript + project configuration in a similar way to QSL to prevent this issue
- Remove the module system and make a single project that contains all the code

We should try to decide which is better here, and make sure it works (run `gradlew clean build`, caching can break proper testing)

**Comment by NoComment1105** [comment]
I actually began work on something similar to the QSL one in an alternative branch, but development stagnated as my time drifted. (dev/buildscript-rewrite iirc)

**Comment by NoComment1105** [comment]
Can't fully remember. I believe it was mostly working and was just in need of polishing. You're welcome to look into it

**Comment by Oliver-makes-code** [comment]
Is this still an issue?

**Comment by SilverAndro** [comment]
Should be fixed with #54 I believe
