### ISSUE TITLE
withId and withName

### ISSUE THREAD

**Issue by lenrik1589** [QuiltMC/quilt-kotlin-libraries#29]
Vanilla Identifiers support using strings to make actual identifier so I believe having jut Identifier be accepted is not the best
https://github.com/QuiltMC/quilt-kotlin-libraries/blob/2a4f49bb896c2e5716a11e315b6cc379428aab78/wrapper/minecraft/src/main/kotlin/org/quiltmc/qkl/wrapper/minecraft/registry/RegistryDsl.kt#L56
so withName is confusing as for me personally it reffers to a TranslatedText or LiteralText name
https://github.com/QuiltMC/quilt-kotlin-libraries/blob/2a4f49bb896c2e5716a11e315b6cc379428aab78/wrapper/minecraft/src/main/kotlin/org/quiltmc/qkl/wrapper/minecraft/registry/RegistryDsl.kt#L68

So a proper withId would be as such
```kotlin
public infix fun T.withId(id: Identifier) {
    Registry.register(registry, id, this)
}


public infix fun T.withId(id: String) {
    Registry.register(registry, if(":" in id || modid == null){
        Identifier(id)
    } else {
        Identifier(modid, id)
    }, this)
}
```

**Comment by Peanuuutz** [comment]
Mean to take on this job.

**Comment by lenrik1589** [comment]
also noticed discrepancy with actual behaviour at https://github.com/QuiltMC/quilt-kotlin-libraries/blob/2a4f49bb896c2e5716a11e315b6cc379428aab78/wrapper/minecraft/src/main/kotlin/org/quiltmc/qkl/wrapper/minecraft/registry/RegistryDsl.kt#L63
which should be
```kotlin
     * If no `modid` is present, it uses `"minecraft:name"` format.
```
