### ISSUE TITLE
Essential don't recognize QKL as FLK

### ISSUE THREAD

**Issue by craftish37** [QuiltMC/quilt-kotlin-libraries#37]
Well, the title is already saying the most, Essential mod can't work without FLK :
![image](https://user-images.githubusercontent.com/63811617/185763099-4a330f2f-887a-4a15-b75e-ca8933fb8fbd.png)

**Comment by TymanWasTaken** [comment]
I already opened an issue with Essential, this is a problem on their side

**Comment by SilverAndro** [comment]
Yeah we already `provides` FLK so this is on their end, and given they're closed source we couldn't try to help even if we wanted to

(Unless someone is in a country where you cant limit right to de-compilation for compatibility and wants to investigate)

**Comment by TymanWasTaken** [comment]
> Yeah we already `provides` FLK so this is on their end, and given they're closed source we couldn't try to help even if we wanted to
> 
> (Unless someone is in a country where you cant limit right to de-compilation for compatibility and wants to investigate)

I don't know how they actually check it but I did suggest they check the `provides` in the mod which would probably be a simple fix, the issue is if they are actually going to or not, I do not think they are a big fan of quilt anyways

**Comment by craftish37** [comment]
#38 Build fixed the issue (:

**Comment by TymanWasTaken** [comment]
> #38 Build fixed the issue (:

Really? For me it doesn't fix the issue, it just causes essential to think that it is still outdated, because 0.1.3 (qkl version) < 1.8.2 (latest flk version)

**Comment by sschr15** [comment]
QKL has a `provides` attribute indicating that mods requiring FLK 1.8.2 are satisfied. My best guess is that Essential is trying to find a mod whose ID is `fabric-language-kotlin` and sees that its nonexistence is equivalent to being outdated since its boot sequence is rather bizarre.

**Comment by SilverAndro** [comment]
Yeah this is clearly going outside of the standard mod resolution, we can't do anything here

**Comment by craftish37** [comment]
Anyway, this issue is "fixed" 🤣
