### ISSUE TITLE
Possible compat issue of some kind involving these libraries

### ISSUE THREAD

**Issue by Sunconure11** [QuiltMC/quilt-kotlin-libraries#44]
![coatlin](https://user-images.githubusercontent.com/5614902/190168120-6de7f14c-4231-4c70-a2a3-3e0cf4c3a282.png)

**Comment by SilverAndro** [comment]
That looks like you put both FLK and QKL in your mods folder, please only use one

**Comment by Sunconure11** [comment]
Looks like that did it, but now I'm off to solve another, unrelated error.
