### ISSUE TITLE
doesn't work with zoomify

### ISSUE THREAD

**Issue by iptory** [QuiltMC/quilt-kotlin-libraries#59]
![image](https://user-images.githubusercontent.com/36310811/208946801-451b2e95-dd1c-41e9-ae53-fc71e1ae7bfd.png)

**Comment by Oliver-makes-code** [comment]
It looks like it expects a newer version of FLK, which we haven't updated to support yet

**Comment by SilverAndro** [comment]
1.0.1 has the updated versions
