### ISSUE TITLE
Modrinth Version vs. Maven Version mismatch

### ISSUE THREAD

**Issue by SylvKT** [QuiltMC/quilt-kotlin-libraries#65]
The Modrinth version numbers and Maven version numbers do not match, which can cause confusion.

**Comment by SilverAndro** [comment]
![image](https://user-images.githubusercontent.com/52360088/226187999-96abaee4-7722-4364-8dd0-8bc4bea6e33b.png)
![image](https://user-images.githubusercontent.com/52360088/226188005-8dae949a-7abf-4a6e-9d74-91b0f9d48cc6.png)
 this seems like the same version to me?

**Comment by triphora** [comment]
![image](https://user-images.githubusercontent.com/60205699/226188442-791e2790-362c-4015-935e-1c23a5acc636.png)
It's only 1.1.1 in the version number and version title.

**Comment by SilverAndro** [comment]
wasnt aware anyone cared about that, changed

also made sure FLK as embedded was added to all versions

**Comment by triphora** [comment]
The original issue, as reported, is *still* not fixed...

![image](https://user-images.githubusercontent.com/60205699/226189206-1b8ea85f-05d3-490c-8248-2ca08cecf3ac.png)

**Comment by SilverAndro** [comment]
yall have too many fields /lh

**Comment by SilverAndro** [comment]
done, gonna link this to #56 rq as a note
