### ISSUE TITLE
Backport kt.1.8.10+flk.1.9.2 to 1.19.2

### ISSUE THREAD

**Issue by SplendidAlakey** [QuiltMC/quilt-kotlin-libraries#67]
Could you, please, backport the newest version to 1.19.2? Some mods now require it, e.g. [Inventory Profiles Next](https://www.curseforge.com/minecraft/mc-mods/inventory-profiles-next):

![image](https://user-images.githubusercontent.com/86702831/227454075-8dd634ab-0712-47a6-a029-6ed6abf65823.png)

**Comment by CantWeAllDisagree** [comment]
This would be super helpful if this could be done as many mods aren't updated past 1.19.2 yet

**Comment by SilverAndro** [comment]
until we get around to publishing `core` separately, you can use dependency overrides or grab it from the maven https://maven.quiltmc.org/repository/release/org/quiltmc/quilt-kotlin-libraries/core/

**Comment by sschr15** [comment]
Are standalone core jars not published to [`org.quiltmc.quilt-kotlin-libraries:core`](https://maven.quiltmc.org/repository/release/org/quiltmc/quilt-kotlin-libraries/core/)?

**Comment by SilverAndro** [comment]
they are, but thats not usable in large distributions like modpacks, or available in mod download interfaces

**Comment by SilverAndro** [comment]
as an update, the snapshot core versions are now aligned with FLK and provide all the same libraries, so all thats left is to actually publish core separately as part of the next release

**Comment by SilverAndro** [comment]
core is now an additional file on both curseforge and modrinth, hopefully this works?

we cant give it unique version requirements without uploading it as its own primary file which i suspect would cause more confusion with your average user

**Comment by SplendidAlakey** [comment]
Thanks! I don't know how additional files work (if at all) for modpacks, but I'll let you know if there are any issues, when I release my next update in a couple of weeks or so.

**Comment by SplendidAlakey** [comment]
Alright, so just an FYI: currently, including additional files in modpacks is possible, but only manually, because the CF app simply has no way of adding or downloading the additional files. In addition to that, the CF app is also capable of downloading the additional files, when included in modpacks, but only if it's the only file from the same project page, i.e. you can't have a main file + an additional files in the same pack. If you attempt to download such a pack, only 1 of the files will get downloaded, seemingly random. That leaves us with everything but the CF app being able to properly download additional files, but they have to be manually included into the `manifest.json`. For now, I'll personally just be using the main file + loader overrides, as long as that doesn't cause issues.

For anyone not having to worry about distributing modpacks or anyone using literally any other launcher, besides CF app, the solution with the additional files works.

I've contacted CF about it and so far they only replied about the impossibility of downloading additional files via the CF app and their replies have been extra slow, so I've decided to just put this out here now.
