### ISSUE TITLE
QKL for fabric language kotlin 1.9.4?

### ISSUE THREAD

**Issue by cootshk** [QuiltMC/quilt-kotlin-libraries#71]
some mods like OptiGUI require FLK 1.9.4 but the latest release only has FLK 1.9.3

**Comment by Octelly** [comment]
Yeah, this seems to be the reason why I can't get UnifiedMetrics working on my server...

**Comment by sschr15** [comment]
QKL now is updated to FLK 1.10.17 with the [latest release](https://modrinth.com/mod/qkl/version/3.0.0+kt.1.9.22+flk.1.10.17)
