### ISSUE TITLE
Cannot use the provided APIs since 2.1.3

### ISSUE THREAD

**Issue by F0Xde** [QuiltMC/quilt-kotlin-libraries#82]
After updating from any earlier version to `2.1.3+kt.1.9.10+flk.1.10.10`, none of the APIs included in core or library can be resolved. I first ran into this when updating the dependencies of my own project, but later also tested and confirmed it by upgrading the QKL version in [quilt-template-mod](https://github.com/QuiltMC/quilt-template-mod).

Depending on core, library and all the included kotlin libraries directly works fine. It seems the provided dependencies aren't listed in the [POM](https://maven.quiltmc.org/repository/release/org/quiltmc/quilt-kotlin-libraries/quilt-kotlin-libraries/2.1.3+kt.1.9.10+flk.1.10.10/quilt-kotlin-libraries-2.1.3+kt.1.9.10+flk.1.10.10.pom) anymore, while they [previously](https://maven.quiltmc.org/repository/release/org/quiltmc/quilt-kotlin-libraries/quilt-kotlin-libraries/2.1.2+kt.1.9.0+flk.1.10.8/quilt-kotlin-libraries-2.1.2+kt.1.9.0+flk.1.10.8.pom) were.

Is this a design choice to have users explicitly depend on only the things they really need, or a bug?

**Comment by Treetrain1** [comment]
Definitely a bug
it would be silly to require manual dependencies

**Comment by SilverAndro** [comment]
this happens even when publishing locally, so seems like #79 changed something that broke it (maybe gradle update? not a lot going on there)

fixing it with the template mod is pretty easy but it should probably be fixed here

---

```patch
- qkl = { module = "org.quiltmc.quilt-kotlin-libraries:quilt-kotlin-libraries", version.ref = "qkl" }
+ qkl_core = { module = "org.quiltmc.quilt-kotlin-libraries:core", version.ref = "qkl" }
+ qkl_library = { module = "org.quiltmc.quilt-kotlin-libraries:library", version.ref = "qkl" }
quilt_loader = { module = "org.quiltmc:quilt-loader", version.ref = "loader" }
quilt_mappings = { module = "org.quiltmc:quilt-mappings", version.ref = "mappings" }

[bundles]
quilted_fabric_api = ["qfapi", "qfapi_deprecated"]
+ qkl = [ "qkl_core", "qkl_library" ]
```

```patch
- modImplementation(libs.qkl)
+ modImplementation(libs.bundles.qkl)
```
