### ISSUE TITLE
Port Kotlin 1.9.22 To 1.20.1

### ISSUE THREAD

**Issue by PolyframeY** [QuiltMC/quilt-kotlin-libraries#93]
Hi, would it be possible to port 1.19.22 kotlin to 1.20.1 quilt? This would be highly appreciated.

**Comment by sschr15** [comment]
All QKL versions, regardless of reported Minecraft or QSL version, have a QKL Core jar which will work assuming you have a recent enough version of Quilt Loader. You can use QKL Core from [QKL 3.0.0](https://modrinth.com/mod/qkl/version/3.0.0+kt.1.9.22+flk.1.10.17) ([direct download](https://cdn.modrinth.com/data/lwVhp9o5/versions/di4GKAZU/quilt-kotlin-libraries-core-3.0.0%2Bkt.1.9.22%2Bflk.1.10.17.jar)) to use Kotlin 1.9.22 and associated libraries.
