### ISSUE TITLE
Update to 1.21

### ISSUE THREAD

**Issue by NotMurPh** [QuiltMC/quilt-kotlin-libraries#97]
Hi, when can we expect the new update for 1.21 ? 🫠

**Comment by woodiertexas** [comment]
Maybe when the Quilt Kotlin devs get around to updating QKL to latest versions of MC.

**Comment by OroArmor** [comment]
Currently there are no maintainers for QKL, meaning that it is very unlikely there will be an update anytime soon. However, we are always willing to accept help from people for updates and would love to see contributions from the public!

**Comment by 770grappenmaker** [comment]
What kinds of tasks are required to support recent versions of Minecraft? I’m not too familiar with QSL/QKL, but I am a big fan of Kotlin and I’d probably be willing to help.

**Comment by OroArmor** [comment]
It's fairly similar to updating a mod. You'll probably want to wait for me to release full QSL as QKL uses a lot of QSL features.
